# Generated by Django 2.2.16 on 2022-11-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_1',
        ),
    ]
