# Generated by Django 2.2.16 on 2022-11-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20221114_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_1',
            new_name='user',
        ),
    ]
